# -*- coding: utf-8 -*-
"""Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blQJgOefEYbUJ7wF4N-_0QaX7i0ErUVt

# Problem Definition
In this Reinforcement Learning framework for trading strategy, the algorithm takes an action (buy, sell or hold) depending upon the current state of the stock price. The algorithm is trained using Q-Learning framework, to help us predict the best action, based on the current stock prices.

### The key components of the RL based framework are :

**Agent**: Trading agent.

**Action:** Buy, sell or hold.

**Reward function:** Realized profit and loss (PnL) is used as the reward function for this case study. The reward depends upon the action:

**Sell:** Realized profit and loss (sell price - bought price)

**Buy:** No reward

**Hold:** No Reward

**State:** Differences of past stock prices for a given time window is used as the state.
"""

# from google.colab import drive
# drive.mount('/content/drive')

"""# Loading the Libraries and Data"""

!pip install scikit-learn
# Load libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pandas import read_csv, set_option
from pandas.plotting import scatter_matrix
import seaborn as sns
from sklearn.preprocessing import StandardScaler
import datetime
import math
from numpy.random import choice
import random


#Import Model Packages for reinforcement learning
from keras import layers, models, optimizers
from keras import backend as K
from collections import namedtuple, deque

#The data already obtained from yahoo finance is imported.
dataset = read_csv('E:/data_new/train.csv',index_col=0)
#acb = read_csv('/content/drive/MyDrive/data_new/ACB_new.csv',index_col=0)
#fpt = read_csv('/content/drive/MyDrive/data_new/FPT_new.csv',index_col=0)
#vcb = read_csv('/content/drive/MyDrive/data_new/VCB_new.csv',index_col=0)

dataset

#Diable the warnings
import warnings
warnings.filterwarnings('ignore')

type(dataset)

# shape
dataset.shape

# peek at data
set_option('display.width', 100)
dataset.head(5)

# describe data
# Set precision for DataFrame display
pd.set_option('display.precision', 3)

# Describe data
dataset.describe()

dataset = dataset.applymap(lambda x: str(x).replace("$", "") if isinstance(x, str) else x)
dataset.rename(columns={'Close/Last': 'Close'}, inplace=True)
dataset['Close'] = pd.to_numeric(dataset['Close'], errors='coerce')

plt.figure(figsize=(25, 10))  # Adjust the figure size as needed
dataset['Close'].plot()

"""# Data Preprocessing"""

#Checking for any null values and removing the null values'''
print('Null Values =',dataset.isnull().values.any())

# Fill the missing values with the last value available in the dataset.
dataset=dataset.fillna(method='ffill')
dataset.head(2)

"""#Training and Testing Data Split"""

X=list(dataset["Close"])
X=[float(x) for x in X]

validation_size = 0.2
#In case the data is not dependent on the time series, then train and test split should be done based on sequential sample
#This can be done by selecting an arbitrary split point in the ordered list of observations and creating two new datasets.
train_size = int(len(X) * (1-validation_size))
X_train, X_test = X[0:train_size], X[train_size:len(X)]

len(X_test)


"""# Implementation Steps For Designing a Reinforcement learning model
•	Importing Libraries

•	Create the agent who will make all decisions

•	Define basic functions for formatting the values, sigmoid function, reading the data file, etc

•	Train the agent

•	Evaluate the agent performance

"""

#Agent in the environment
import numpy as np
import random
from collections import deque
from keras.models import Sequential, load_model
from keras.layers import Dense
from keras.optimizers import Adam

class Agent:
    def __init__(self, state_size, is_eval=False, model_name=""):
        self.state_size = state_size  #state vector size typically refers to the number of features or dimensions used to represent each state, not the number of data points.
        self.action_size = 3          #buy,sell,hold
        self.memory = deque(maxlen=1000)  # Initialize a memory buffer to store past experiences
        self.inventory = []                # Initialize an inventory to track bought stocks
        self.model_name = model_name       # Set the name of the model file to load or save
        self.is_eval = is_eval             # Flag to indicate if the agent is in evaluation mode
        self.gamma = 0.95                  # Set the discount factor for future rewards
        self.epsilon = 1.0                 # Set the exploration rate (epsilon) for epsilon-greedy strategy
        # self.epsilon_min = 0.01
        # self.epsilon_decay = 0.995
        self.model = load_model(model_name) if is_eval else self._model()

    def _model(self):
        model = Sequential()
        #add input layer
        model.add(Dense(units=64, input_dim=self.state_size, activation="relu"))
        #add hidden layer
        model.add(Dense(units=32, activation="relu"))
        model.add(Dense(units=8, activation="relu"))
        #add output layer
        model.add(Dense(self.action_size, activation="linear"))
        # Compile the model with mean squared error loss and Adam optimizer
        model.compile(loss="mse", optimizer=Adam(learning_rate=0.001))
        return model

#epsilon-greedy approch is implemented to find action
    def act(self, state):
        # In training mode, with probability epsilon, choose a random action to explore
        if not self.is_eval and random.random() <= self.epsilon:
            return random.randrange(self.action_size)
        #exploitation
        # Otherwise, predict Q-values for each action and choose the action with the highest Q-value
        options = self.model.predict(state)
        return np.argmax(options[0])


#Helper functions
import numpy as np
import math

# prints formatted price
def formatPrice(n):
    return ("-$" if n < 0 else "$") + "{0:.2f}".format(abs(n))

# # returns the vector containing stock data from a fixed file
# def getStockData(key):
#     vec = []
#     lines = open("data/" + key + ".csv", "r").read().splitlines()

#     for line in lines[1:]:
#         vec.append(float(line.split(",")[4])) #Only Close column

#     return vec

# returns the sigmoid
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# returns an an n-day state representation ending at time t
# This ensures that the state representation always consists of n consecutive closing prices,
# even if it requires padding with the initial closing price.
def getState(data, t, n): # n is window size and t is at time t
    d = t - n + 1
    block = data[d:t + 1] if d >= 0 else -d * [data[0]] + data[0:t + 1] # pad with t0
    #block is which is the for [1283.27002, 1283.27002]
    res = []
    for i in range(n - 1):
        res.append(sigmoid(block[i + 1] - block[i]))
    return np.array([res])

# Plots the behavior of the output
def plot_behavior(data_input, states_buy, states_sell, profit):
    fig = plt.figure(figsize = (15,5))
    plt.plot(data_input, color='r', lw=2.)
    plt.plot(data_input, '^', markersize=10, color='m', label = 'Buying signal', markevery = states_buy)
    plt.plot(data_input, 'v', markersize=10, color='k', label = 'Selling signal', markevery = states_sell)
    plt.title('Total gains: %f'%(profit))
    plt.legend()
    #plt.savefig('output/'+name+'.png')
    plt.show()

"""# Training"""

#Training

window_size = 10
agent = Agent(window_size)
#In this step we feed the closing value of the stock price
data = X_train
l = len(data) - 1
#
batch_size = 32
#An episode represents a complete pass over the data.
episode_count = 1000

# Create best_episode to save episode have highest profit
highest_profit = float('-inf')
best_episode = -1

# Create transaction_counts to save info about each transactions
transaction_counts = []

for e in range(episode_count + 1):
    print("Running episode " + str(e) + "/" + str(episode_count))
    state = getState(data, 0, window_size + 1) #agent observes current state
    total_profit = 0
    agent.inventory = []
    states_sell = []
    states_buy = []

    for t in range(l):
        action = agent.act(state)    # selects an action based on current state
        next_state = getState(data, t + 1, window_size + 1)
        reward = 0

        if action == 1:  # buy
            agent.inventory.append(data[t])
            states_buy.append(t)

        elif action == 2 and len(agent.inventory) > 0:  # sell
            bought_price = agent.inventory.pop(0)
            reward = max(data[t] - bought_price, 0)
            total_profit += data[t] - bought_price
            states_sell.append(t)

        done = True if t == l - 1 else False
        agent.memory.append((state, action, reward, next_state, done))
        state = next_state

        if done:
            print("--------------------------------")
            print("Total Profit: " + formatPrice(total_profit))
            print("--------------------------------")
            plot_behavior(data, states_buy, states_sell, total_profit)

    # Update episode has highest profit
    if total_profit > highest_profit:
        highest_profit = total_profit
        best_episode = e

    # Count total transactions
    transaction_count = len(states_buy) + len(states_sell)
    transaction_counts.append((e, transaction_count, total_profit))

    # Save model(2ep)
    if e % 2 == 0:
        agent.model.save("E:/checkpoint/INTU/model_ep" + str(e) + ".keras")

# show highest profit
print(f"The episode with the highest profit is {best_episode} with a profit of {formatPrice(highest_profit)}")

# Sort transaction_counts with descending and show top 10
top_transactions = sorted(transaction_counts, key=lambda x: x[1], reverse=True)[:10]
print("\nTop 10 episodes with the most transactions:")
for episode, count, profit in top_transactions:
    print(f"Episode {episode}: {count} transactions, Total Profit: {formatPrice(profit)}")

import matplotlib.pyplot as plt

# Assuming 'transaction_counts' is available from the previous code
# transaction_counts = [(episode_number, transaction_count, total_profit), ...]

episodes = [item[0] for item in transaction_counts]
profits = [item[2] for item in transaction_counts]

plt.figure(figsize=(12, 6))
plt.plot(episodes, profits)
plt.xlabel("Episode")
plt.ylabel("Total Profit")
plt.title("Total Profit per Episode (Training Data)")
plt.grid(True)
plt.show()

# Calculate accuracy (assuming a profit > 0 is a "correct" prediction)
correct_predictions = sum(1 for profit in profits if profit > 0)
accuracy = (correct_predictions / len(profits)) * 100

print(f"Accuracy on training data: {accuracy:.2f}%")

print(f"The episode with the highest profit is {best_episode} with a profit of {formatPrice(highest_profit)}")

#Q-Learning Model
print(agent.model.summary())

from tensorflow.keras.models import load_model
import json
import h5py

# Path to the .keras model file
model_path = "E:/checkpoint/INTU/model_ep1000" + ".keras"

# Load the Keras model
model = load_model(model_path)

# Print the model summary to see its architecture
print("Model Summary:")
model.summary()

# Load model configuration (architecture)
model_config = model.to_json()
config_data = json.loads(model_config)
print("\nConfig.json content:")
print(json.dumps(config_data, indent=2))  # Pretty-print JSON config data

# Access the metadata (if available in the .keras file)
if hasattr(model, "_get_metadata"):
    metadata = model._get_metadata()
    print("\nMetadata.json content:")
    print(json.dumps(metadata, indent=2))
else:
    print("\nNo metadata found.")


"""# Testing"""

#agent is already defined in the training set above.
test_data = X_test
data = X_train
window_size = 10
l_test = len(test_data) - 1
state = getState(test_data, 0, window_size + 1)  #Initializes the state by calling the getState function with the test data, starting at index 0, and a window size of window_size + 1
total_profit = 0  #initilaize profit
is_eval = True    #Indicates that the agent is in evaluation mode.
done = False       # Indicates whether the evaluation is complete or not.
#Initialize empty lists to store the indices where the agent decides to sell or buy during evaluation.
states_sell_test = []
states_buy_test = []
#Get the trained model
model_name = "E:/checkpoint/INTU/model_ep106" + str(e) + ".keras"
agent = Agent(window_size, is_eval, model_name)
state = getState(data, 0, window_size + 1)
total_profit = 0
agent.inventory = [] #Resets the agent's inventory for evaluation.

#Sharpe ratio based on the test data and total profit.
def calculate_sharpe_ratio(data, total_profit):
    # Calculate daily returns
    daily_returns = np.diff(data) / data[:-1]

    # Calculate average daily return and standard deviation of daily return
    avg_daily_return = np.mean(daily_returns)
    std_daily_return = np.std(daily_returns)

    # Assuming risk-free rate is 0 for simplicity
    risk_free_rate = 0

    # Calculate Sharpe ratio
    sharpe_ratio = (avg_daily_return - risk_free_rate) / std_daily_return

    return sharpe_ratio

"""# trading simualtion

•	A loop iterates over each data point in the test data.

•	At each time step:
1.	The agent's action is determined using the current state.
2.	Based on the action, the agent may buy, sell, or hold.
3.	The reward is calculated based on the action taken.
4.	Metrics such as total profit, number of trades, and winning trades are updated accordingly.
5.	The state, action, reward, and next state are appended to the agent's memory.
6.	If it's the last time step, done is set to True.




"""

# Define variables to track metrics
total_profit = 0
sharpe_ratio = 0
win_rate = 0
baseline_profit = 0
baseline_sharpe_ratio = 0
baseline_win_rate = 0
num_trades = 0
num_winning_trades = 0

# Define lists to store trade information
states_sell_test = []
states_buy_test = []

# Iterate over the test data
for t in range(l_test):
    # Get the agent's action
    action = agent.act(state)
    next_state = getState(test_data, t + 1, window_size + 1)
    reward = 0

    # Buy action
    if action == 1:
        agent.inventory.append(test_data[t])
        states_buy_test.append(t)
        print("Buy: " + formatPrice(test_data[t]))

    # Sell action
    elif action == 2 and len(agent.inventory) > 0:
        bought_price = agent.inventory.pop(0)
        reward = max(test_data[t] - bought_price, 0)
        total_profit += test_data[t] - bought_price

        # Update trade metrics
        num_trades += 1
        if reward > 0:
            num_winning_trades += 1

        states_sell_test.append(t)
        print("Sell: " + formatPrice(test_data[t]) + " | profit: " + formatPrice(test_data[t] - bought_price))

    # Update agent's memory
    if t == l_test - 1:
        done = True
    agent.memory.append((state, action, reward, next_state, done))
    state = next_state

# Calculate metrics
# Total profit
total_profit = total_profit

# Sharpe ratio
# Assuming risk-free rate is 0 for simplicity
# You may need to adjust this calculation based on your specific context
sharpe_ratio = calculate_sharpe_ratio(test_data, total_profit)

# Win rate
win_rate = num_winning_trades / num_trades if num_trades > 0 else 0

# Comparison with baseline strategy
# Define a baseline strategy (e.g., buy and hold)
baseline_profit = test_data[-1] - test_data[0]  # Profit from buy and hold strategy
baseline_sharpe_ratio = 0  # Adjust this based on your risk-free rate
baseline_win_rate = 0  # No trades in the baseline strategy

# Print metrics
print("------------------------------------------")
print("Total Profit: " + formatPrice(total_profit))
print("Sharpe Ratio: " + str(sharpe_ratio))
print("Win Rate: " + str(win_rate))
print("Baseline Profit: " + formatPrice(baseline_profit))
print("Baseline Sharpe Ratio: " + str(baseline_sharpe_ratio))
print("Baseline Win Rate: " + str(baseline_win_rate))
print("------------------------------------------")

# Plot behavior
plot_behavior(test_data, states_buy_test, states_sell_test, total_profit)

# Create an empty list to store the trading simulation results
predicted_prices_data = []

# Iterate through the states_buy_test list, considering the corresponding sell action
for i in range(len(states_buy_test)):
    buy_date = states_buy_test[i]
    buy_price = test_data[buy_date]

    # Append buy data
    predicted_prices_data.append([dataset.index[buy_date], 'Buy', buy_price])

    # Check if a corresponding sell action exists
    if i < len(states_sell_test):
        sell_date = states_sell_test[i]
        sell_price = test_data[sell_date]

        # Append sell data
        predicted_prices_data.append([dataset.index[sell_date], 'Sell', sell_price])

# Create the DataFrame
predicted_prices = pd.DataFrame(predicted_prices_data, columns=['Date', 'Buy/Sell', 'Price'])

# Display the DataFrame
#predicted_prices.to_csv('/content/drive/MyDrive/REL301m/data_new/predicted_prices_fpt.csv')

predicted_prices

test = read_csv('E:/data_new/train.csv')
train = read_csv('E:/data_new/test.csv')
val = read_csv('E:/data_new/val.csv')

if isinstance(test_data, list):
    test_data = pd.DataFrame(test_data, columns=['Close'])
test_data['label'] = test_data['Close'].diff().apply(lambda x: 'buy' if x > 0 else ('sell' if x < 0 else 'hold'))

# Assuming 'predicted_prices' and 'acb_label' DataFrames are already defined
import pandas as pd

# Convert 'Date' column to datetime objects
predicted_prices['Date'] = pd.to_datetime(predicted_prices['Date'])
test['Date'] = pd.to_datetime(test['Date'])

# Merge the DataFrames based on the 'Date' column
merged_df = pd.merge(predicted_prices, test, on='Date', how='inner')

# Calculate accuracy based on 'Buy/Sell' and 'Label' columns
correct_predictions = 0
total_predictions = 0

for index, row in merged_df.iterrows():
    if row['Buy/Sell'] == 'Buy' and row['label'] == "buy":
        correct_predictions += 1
    elif row['Buy/Sell'] == 'Sell' and row['label'] == 'sell':
        correct_predictions += 1
    total_predictions += 1

accuracy = (correct_predictions / total_predictions) * 100 if total_predictions > 0 else 0
print(f"Accuracy based on labels: {accuracy:.2f}%")

# Print the merged DataFrame for verification
merged_df

# Assuming 'merged_df' DataFrame is already created as shown in the original code.

# Filter the DataFrame to show only incorrect predictions
incorrect_predictions = merged_df[
    (merged_df['Buy/Sell'] == 'Buy') & (merged_df['label'] != 'buy') |
    (merged_df['Buy/Sell'] == 'Sell') & (merged_df['label'] != 'sell')
]

print("Incorrect Predictions:")
incorrect_predictions

from sklearn.metrics import f1_score

# Assuming 'merged_df' DataFrame is already created as shown in the original code.

# Extract true labels and predicted labels
true_labels = merged_df['label'].map({'buy': 1, 'sell': 0, 'hold': 2})  # Map labels to numerical values
predicted_labels = merged_df['Buy/Sell'].map({'Buy': 1, 'Sell': 0})  # Map predictions to numerical values

# Calculate F1-score (ignoring 'hold' predictions)
f1 = f1_score(true_labels, predicted_labels, average='weighted')

print(f"F1-score on training data: {f1:.4f}")
